model = "Qwen/Qwen3-4B-Instruct-2507"

[env]
id = "textworld_cooking_env"

[env.args]
difficulties = [1]
max_turns=10


[inference]
gpus = 2

[inference.args]
enforce_eager = true

[trainer]
gpus = 2


[trainer.args]
run_name = "textworld_cooking_env-max_turns:10-batch_size:128-rollouts:8-qwen3-4b"
micro_batch_size = 8
rollouts_per_example = 8
logprobs_chunk_size = 8
gradient_checkpointing = false
batch_size = 128
max_steps = 100
max_tokens = 512
max_seq_len = 1024

[trainer.args.chat_template_kwargs]
enable_thinking = false
